const ActionTypes = {
    UPDATE_FIRST_COORDINATE: 'UPDATE_FIRST_COORDINATE',
    UPDATE_SECOND_COORDINATE: 'UPDATE_SECOND_COORDINATE',
    UPDATE_DISTANCE_1: 'UPDATE_DISTANCE_1',
    UPDATE_DISTANCE_2: 'UPDATE_DISTANCE_2'
};

export default ActionTypes;
